export const search_result = {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: "/eRfANc4xSRNaR8E9fUI9hdLkCWB.jpg",
            genre_ids: [35, 18],
            id: 425980,
            media_type: "movie",
            original_language: "en",
            original_title: "Brad's Status",
            overview: "Although Brad has a satisfying career, a sweet wife and a comfortable life in suburban Sacramento, things aren't quite what he imagined during his college glory days. When he accompanies his musical prodigy son on a university tour, he can't help comparing his life with those of his four best college friends who seemingly have more wealthy and glamorous lives. But when circumstances force him to reconnect with his former friends, Brad begins to question whether he has really failed or if their lives are actually more flawed than they appear.",
            popularity: 5.422,
            poster_path: "/uXiNpvig7EMq18VyNBUTlWrmN0q.jpg",
            release_date: "2017-09-14",
            title: "Brad's Status",
            video: false,
            vote_average: 6,
            vote_count: 137,
        },
        {
            adult: false,
            backdrop_path: "/eRfANc4xSRNaR8E9fUI9hdLkCWB.jpg",
            genre_ids: [35, 18],
            id: 425980,
            media_type: "movie",
            original_language: "en",
            original_title: "Brad's Status",
            overview: "Although Brad has a satisfying career, a sweet wife and a comfortable life in suburban Sacramento, things aren't quite what he imagined during his college glory days. When he accompanies his musical prodigy son on a university tour, he can't help comparing his life with those of his four best college friends who seemingly have more wealthy and glamorous lives. But when circumstances force him to reconnect with his former friends, Brad begins to question whether he has really failed or if their lives are actually more flawed than they appear.",
            popularity: 5.422,
            poster_path: "/uXiNpvig7EMq18VyNBUTlWrmN0q.jpg",
            release_date: "2017-09-14",
            name: "Brad's Status",
            video: false,
            vote_average: 6,
            vote_count: 137,
        }
    ],
    total_pages: 122,
    total_results: 2433,
}